# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20170121_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='', max_length=100),
        ),
    ]
